"""add upvote and downvote columns

Revision ID: 527cef003245
Revises: 779614eabf3f
Create Date: 2021-08-17 06:06:51.173643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527cef003245'
down_revision = '779614eabf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('downvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'downvote')
    op.drop_column('posts', 'upvote')
    # ### end Alembic commands ###
