"""update on comments table

Revision ID: 779614eabf3f
Revises: 8c4a3e67a1d5
Create Date: 2021-08-14 08:58:02.742309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779614eabf3f'
down_revision = '8c4a3e67a1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comments', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comments')
    # ### end Alembic commands ###
